### ISSUE TITLE
Issue in Running the APP

### ISSUE THREAD

**Issue by neomatrixgem** [e-gov/fox#10]
Hi,  I am pretty new to this architecture, I have tried the below but don't see any UI or any interface.  

```
++ git clone
++ jekyll serve
++ Browse http://127.0.0.1:4000, I see the all the files and folders inside.. 
```

Am i missing something or this is what is expected ? 

Please help.

**Comment by neomatrixgem** [comment]
Seems like i have fixed it, had some issues with go complication.  Now when i try : http://localhost:8090/fox/status

I see the below : 
{"timeSinceLastOK":131,"timeSinceLastNOK":71619,"currentRequestCount":1,"nodeName":"."}

But is there is any success/failure criteria to test this application ?

**Comment by andreskytt** [comment]
The FoxAPI should implement the https://github.com/e-gov/fox/blob/master/FoxAPI.yaml API. So that's your success criteria for now. Does that answer the question? Please close the issue, if it does. There is now a jekyll site with a rudimentary UI to test the API.

**Comment by neomatrixgem** [comment]
Thanks for your help.  I will check it and let you know ASAP.

**Comment by neomatrixgem** [comment]
I have followed the README and its working fine but i have the below issues : 

++ Not able to open the UI when i use http://localhost:8090/
++ The only output i see is when i run the query as : localhost:8090/fox/status

Is there anyway i could change the localhost to the IP of the server ? also to see the UI what changes i need to do so that it will work.

**Comment by andreskytt** [comment]
Did you do the part with 'Run jekyll serve from the static folder.'? At what port did it start at and what does it say when you connect?

**Comment by livenson** [comment]
localhost:8090 is hardcoded in index.html: https://github.com/e-gov/fox/blob/master/static/index.html#L125 . So just patch it locally.

**Comment by andreskytt** [comment]
There have been many changes to the UI and API. Has this one been resolved? If so, please close

**Comment by andreskytt** [comment]
No longer an issue, apparently. Reopen, if the new setup still gives problems
