### ISSUE TITLE
Web UI is POSTing foxes to an incorrect URL

### ISSUE THREAD

**Issue by livenson** [e-gov/fox#16]
According to spec it should be a POST to **/fox/foxes/**. In reality it's implemented in both web UI and REST backend as **/fox/add**.

**Comment by andreskytt** [comment]
The YAML goes 

```
  /fox/add:
    post:
      description: 
        Create a new `Fox` object with the data submitted. Returns the **uuid** of the `Fox` created. If the Fox exists, it is overwritten without warning.
```

While, this is slightly off-pattern (a post to /fox/foxes/add would be more appropriate) the current idea is not to build in any limitations to the fox IDs. A POST to a URL /fox/foxes/add might mean an update to a fox with an ID "add" or a new fox. Any other ideas how to get around this?

**Comment by livenson** [comment]
Well, I can comment on how we did it in https://github.com/opennode/nodeconductor -- which I think is correct enough. Adapting to the fox scenario:
- Creation is done by POSTing to /fox/foxes/ . If you provide ID parameter, it's ignored.
- Update is done by PUT/PATCHting to /fox/foxes/<id>/ . Adding ID parameter into a path highlights that it's a mandatory parameter.
- Deletion is then done by DELETE /fox/foxes/<id>/.
- For actions that don't fit into REST nicely, i.e. for more of RPC actions, we have taken a convention to POST to /fox/foxes/<id>/action/   (action could be e.g. 'cook the fox')

**Comment by andreskytt** [comment]
Should work like so now. Testing is becoming a chore, will start working on a test suite.
