### ISSUE TITLE
Abuse of REST for delete operations

### ISSUE THREAD

**Issue by livenson** [e-gov/fox#17]
At the moment, spec defines deletion of a fox as a GET operation to a certain url: /fox/foxes/{foxId}/delete .
According to REST, GET should always be a non-modifying, idempotent operation. Moreover, such an approach is basically a custom RPC. Suggestion is to change spec to use rather **DELETE /fox/foxes/{foxID}/**.

**Comment by andreskytt** [comment]
Done.
