### ISSUE TITLE
Integrate with an external authentication service

### ISSUE THREAD

**Issue by andreskytt** [e-gov/fox#2]
Choose an external solution that
- is able to respond to SAML assertions about URLs being accessible for a given user
- is able to do so using HTTP

Integrate it with the FoxAPI

**Comment by livenson** [comment]
http://taat.edu.ee/ ?

**Comment by livenson** [comment]
@andreskytt , did you mean authentication or authorization service here? From the description seems more of authZ. In this case, why cannot it be part of the fox micro-service? AuthZ systems are typically closer to the application as they need to be domain-aware.

**Comment by andreskytt** [comment]
There is a need for both. Something needs to provide the end user with a session key. And there needs to be a place where I can validate that a given session can perform a given operation with a given URL. 

In gov setup, the roles and responsibilities are typically handled by a separate LDAP box. So possibly there is a need for  a AuthZ microservice that can query that box and talk to a session store. 

So the flow would be like so:
- user authenticates, a session with context is created at a session store
- the UI accesses the FoxAPI providing a session
- the FoxAPI provides the session and its identifier to a AuthZ service
- The AuthZ service gets the session context from the session store
- The AuthZ maps the session context to a LDAP requests and validates the request
- FoxAPI provides the service or denies it

It might make sense to have AuthZ as a library rather than a service and most of this sounds like it should be part of any microservice setup. 

Does this make sense and what can we do not to invent the wheel?

**Comment by livenson** [comment]
- I think what you've initially proposed goes under: https://www.appsflyer.com/blog/how-we-solved-authentication-and-authorization-in-our-microservices-architecture/
- And I prefer more of this approach: https://blog.andyet.com/2015/05/12/micro-services-user-info-and-auth/ . It's arguably less in the spirit of micro-services and more of SOA, but imho easier to comprehend/setup/debug.

To summarise how I'd see it: first it's important to split authN and authZ. 

AuthN can be done by a large number of methods - usernames/password, oauth2, eid, apache web server proxy-based approach (when a mod_xxx processes and validates request, passing only extracted credentials in a username/password manner). So from the perspective of a micro-service setup, I'd say that requests between micro-services should be based on some tokens (potentially cryptographic with a limited timespan and metadata). And that there should be a micro-service/gateway for generating these tokens. The token can optionally be revealed to the user (e.g. to be able to use it from a browser app going for some micro-services directly, should the need come up)

AuthZ is more coupled within a micro-service. I.e. each micro-service should have a method, probably a library, that would return request user identity + optional metadata. A micro-service should then be reading the rules (local or coming from a central repository/a'la LDAP) defining ACLs for URLs.

Drawback:
- more code in a micro-service

Profit:
- easier to do e2e testing against a single aspect of an application, speeds up dev cycle.

**Comment by andreskytt** [comment]
Your approach of coupling AuthZ with the micro-service makes sense. If there is a session validation gateway, it should be separate from load balancing. It adds an additional latency layer but it should not be a problem in our moderately loaded case. I kinda like the idea of cryptographic tokens. Have you seen a good implementation? 

Anyhow. This is my reflection of your idea:
![component](https://cloud.githubusercontent.com/assets/7289862/12959240/471762da-d03e-11e5-9a0d-b25d5a0b4245.png)

Every API instance contains a AuthZLib instance, that, given a sessionID, can talk to the UserInfoAPI to gain session context and then query LDAP based on the results.

LoginService provides a UI and an API (probably authenticated via https certs) for consumers to authenticate themselves and uses an (external?) SessionMint that can generate cryptographic tokens.

Token gateway can validate these tokens and pass on requests as they come in. 

Sounds right?

**Comment by livenson** [comment]
Cryptotokens: I've worked with Openstack's: https://www.mirantis.com/blog/understanding-openstack-authentication-keystone-pki/  . Openstack has recently also introduced Heroku's Fernet tokens: http://dolphm.com/openstack-keystone-fernet-tokens/ , which could be a good trade-off for such kind of communication (needs more thinking/testing though).

AuthZLib -- with cryptotoken, the library can extract session context from the token, removing the need for extra calls to UserInfoAPI (for basic scenarios).

I'm not sure about the TokenGateway, what's the added value of it? Parsing a crypto-token typically means validation of it as well.

**Comment by livenson** [comment]
After a bit of additional meditation:

So a separate UserInfoAPI means basically online validation of requests and conceptually is the same as Oauth2 (with all its gains and drawbacks). Crypto-tokens are basically equal to offline processing with X509 certs (with all the gains and drawbacks).

Soo, I guess it's about which approach is better.

**Comment by andreskytt** [comment]
Well, the token gateway idea was take from 

> And I prefer more of this approach: https://blog.andyet.com/2015/05/12/micro-services-user-info-and-auth/ . It's arguably less in the spirit of micro-services and more of SOA, but imho easier to comprehend/setup/debug.

But you are right, parsing it means validation as well. So what about two libraries: AuthN encapsulating parsing of Fernet tokens (which I like) and AuthZ for validating the result against an external entity? No UserInfo API and no TokenGateway. Less parts, I like this.

**Comment by andreskytt** [comment]
Closing, replacing with https://github.com/e-gov/fox/issues/23 and https://github.com/e-gov/fox/issues/24. Will update the architecture document shortly.
