### ISSUE TITLE
Integrate with external SSO service

### ISSUE THREAD

**Issue by andreskytt** [e-gov/fox#3]
Choose a SSO provider and integrate the FoxAPI (validation) and FoxUI (creation and desctruction) with it.

**Comment by livenson** [comment]
What's the business value of such a thing? Not clear why username/password wouldn't be enough for https://www.ria.ee/riigiarhitektuur/wiki/doku.php?id=an:rebasteregister .

Also, did you mean SSO like something SAML-based/Shibboleth or rather more lightweight external authn like oauth2/eid?

**Comment by andreskytt** [comment]
The business value is _not_ having usernames, passwords and roles in the app. eIDAS as well as general authentication recommendations for the Estonian public sector (about to be institutionalised) mean these sorts of apps must use an external provider. Shibboleth would be preferable as it fits with the plans of a central government SSO/auth sevice.

**Comment by andreskytt** [comment]
Alright, let's leave the entire thing out of scope, shall we? For the moment we'll assume that there is an external party able to supply us with cryptotokens and we'll implement a mock to do just that. Closing, opened a new issue for the mock api https://github.com/e-gov/fox/issues/22
