### ISSUE TITLE
Implement S3 support in the FoxAPI

### ISSUE THREAD

**Issue by andreskytt** [e-gov/fox#5]
The FoxAPI should be able to persist objects using a S3 interface

**Comment by livenson** [comment]
What's the motivation for using s3 for this? Immediately questions like credential management come into picture -- isn't it taking scope away? What's wrong with basic file system?

**Comment by andreskytt** [comment]
The current idea is to have all of the load balancing, concurrency management etc. implemented by the storage layer to keep the app itself simple. The file system does not do that.

**Comment by livenson** [comment]
Well, to be fare, FSs like ceph FS do that. And concurrent writes to AWS S3 need to still be managed on the app side (what will happen if there are two concurrent writes to the same s3 blob? S3 API is not clear about what will happen).

**Comment by andreskytt** [comment]
Well, that's a decision, then. Let's stick with FS. I'll update the architecture. One more thing to worry about. Thanks!
