### ISSUE TITLE
Jekyll instructions in README are referring to something unclear 

### ISSUE THREAD

**Issue by livenson** [e-gov/fox#8]
1. git clone
2. jekyll serve
3. Go to localhost:4000

```
Forbidden

no access permission to `/'
WEBrick/1.3.1 (Ruby/2.0.0/2014-05-08) at localhost:4000
```

**Comment by martinpaljak** [comment]
Indeed, this is not a jekyll site, the yaml is for swagger.

**Comment by andreskytt** [comment]
Will clear it up later today

**Comment by livenson** [comment]
Perhaps then you can add a link for viewing API directly?
http://editor.swagger.io/#/?import=https:%2F%2Fraw.githubusercontent.com%2Fe-gov%2Ffox%2Fmaster%2FFoxAPI.yaml

**Comment by andreskytt** [comment]
It should now be better, added the link as well.
